easy_admin:
    design:
        menu:
            - { label: 'Homepage', url: '/', rel: 'index' }
            - label: 'Product'
              children: ['Product', 'ProductCategory', 'ProductSubCategory']
            - label: 'Order'

            - label: 'User'
              children: ['User']
    entities:

        Product:
            class: App\Entity\Product
            label: 'Лот'
            list:
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'code' , label: 'Code', type: 'string'}
                    - {property: 'about' , label: 'Name'}
                    - {property: 'category.name' , label: 'Category'}
            form:
                fields:
                    - { type: 'tab' , label: 'Basic Information' }
                    - 'code'
                    - 'category'
                    - 'owner'
                    - 'price'
                    - { type: 'tab', label: 'About Information', icon: 'info' }
                    - 'about'
                    - 'startAt'
                    - 'finishAt'
                    - { type: 'tab', label: 'Photo Information', icon: 'photo' }
                    - 'photo'

            templates:
                edit: 'admin/Product/edit.html.twig'
                new: 'admin/Product/new.html.twig'

        ProductCategory:
            class: App\Entity\ProductCategory
            label: 'Категория'
            list:
                dql_filter: 'entity.parent IS NULL'
                fields: ['id', 'name']
            form:
                fields: ['name']

        ProductSubCategory:
            class: App\Entity\ProductCategory
            label: 'Подкатегория'
            list:
                dql_filter: 'entity.parent > 0'

        User:
            class: App\Entity\User
