easy_admin:
    design:
        menu:
            - { label: 'Homepage', url: '/', rel: 'index' }
            - label: 'Product'
              children: ['Product', 'ProductCategory', 'ProductSubCategory']
            - label: 'Order'

            - label: 'User'
              children: ['User']
    entities:

        Product:
            class: App\Entity\Product
            label: 'Лот'
            list:
                actions: ['active', 'hide']
                fields:
                    - {property: 'id' , label: 'ID'}
                    - {property: 'name' , label: 'Name', type: 'string'}
                    - {property: 'code' , label: 'Code', type: 'string'}
                    - {property: 'price' , label: 'Price'}
                    - {property: 'category.name' , label: 'Category'}
                    - {property: 'status' , label: 'Status'}
                    - {property: 'photo', label: 'Photo', type: 'image', base_path: '/images/products' }
            form:
                fields:
                    - { type: 'group' , label: 'Basic Information' }
                    - 'name'
                    - 'code'
                    - 'category'
                    - 'owner'
                    - 'price'
                    - { type: 'group', label: 'About Information', icon: 'info' }
                    - { property: 'about', type: 'fos_ckeditor'}
                    - { property: 'startAt', format: 'j/n/Y'}
                    - { property: 'finishAt', format: 'd/m/Y'}
                    - { type: 'group', label: 'Photo Information', icon: 'photo' }
                    - { property: 'photoFile', type: 'vich_file' }

            templates:
                edit: 'admin/Product/edit.html.twig'
                new: 'admin/Product/new.html.twig'

        ProductCategory:
            class: App\Entity\ProductCategory
            label: 'Категория'
            list:
                dql_filter: 'entity.parent IS NULL'
                fields: ['id', 'name']
            form:
                fields: ['name']

        ProductSubCategory:
            class: App\Entity\ProductCategory
            label: 'Подкатегория'
            list:
                dql_filter: 'entity.parent > 0'

        User:
            class: App\Entity\User
